### PR TITLE
staging to master

### PR DESCRIPTION
**Pull request by dnsos**
This PR adds the latest changes on `staging` to `master`. The changes are several dependency updates.

### CODE REVIEW

**Comment by dnsos** [comment]
This is currently not ready to be merged as we have a problem with the upgrade of the `purgecss-webpack-plugin`. Apparently the plugin now purges too many selectors (of Bulma?!), so most styles are completely messed up. Removing the plugin from `nuxt.config.js` solves that, but that can't be the solution. I recall that we've had this issue before...

@fabianmoronzirfas could you help out?

**Comment by fabianmoronzirfas** [comment]
Hm wired error. Maybe we can replace it with https://github.com/Developmint/nuxt-purgecss

**Comment by fabianmoronzirfas** [comment]
Last commit should fix that. Looks good locally.

**Review by fabianmoronzirfas — APPROVED** [review]
LGTM. @dnsos You have more knowledge about the site. I added the nuxt-purgecss and it looks like the builds are fine. If you feel that nothing is broken - feel free to merge

**Comment by dnsos** [comment]
@fabianmoronzirfas thanks for the fix! The site works as it should - merging this now.

**Pull request merged**
