### PR TITLE
New Pics Events

### PR DESCRIPTION
**Pull request by Gosia-cityLAB**
Please create your PR against the staging branch. Not master!
# Title of your pull request

short description what is 

++ Added or new
-- removed

reference issues using

\#NUMBER

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
@Gosia-cityLAB Didyou check is all your images are displayed correctly?

**Review by dnsos — COMMENTED** [review]
It seems that the images added in this PR were also added in [this commit](https://github.com/technologiestiftung/citylab-microsite/commit/cd2fc794f3f006bd748f059f1eabaa3bb110c7a4) which is already merged into `master`. I guess we can close this PR without merging. @fabianmoronzirfas or @Gosia-cityLAB can you confirm this?

**Comment by fabianmoronzirfas** [comment]
@dnsos Thanks. I guess I messed up :-/

@Gosia-cityLAB can you please review this https://deploy-preview-108--citylab-berlin.netlify.app/

**Comment by dnsos** [comment]
Closing this since the files added in this PR are already present in the `master` branch.

**Pull request closed without merging**
